const gameData = [
  { pais: 'Afganistán', capital: 'Kabul'},
  { pais: 'Albania', capital: 'Tirana'},
  { pais: 'Alemania', capital: 'Berlín'},
  { pais: 'Andorra', capital: 'Andorra la Vieja'},
  { pais: 'Angola', capital: 'Luanda'},
  { pais: 'Antigua y Barbuda', capital: 'Saint John’s'},
  { pais: 'Arabia Saudita', capital: 'Riad'},
  { pais: 'Argelia', capital: 'Argel'},
  { pais: 'Argentina', capital: 'Buenos Aires'},
  { pais: 'Armenia', capital: 'Ereván'},
  { pais: 'Australia', capital: 'Camberra'},
  { pais: 'Austria', capital: 'Viena'},
  { pais: 'Azerbaiyán', capital: 'Bakú'},
  { pais: 'Bahamas', capital: 'Nasáu'},
  { pais: 'Bangladés', capital: 'Daca'},
  { pais: 'Barbados', capital: 'Bridgetown'},
  { pais: 'Baréin', capital: 'Manama'},
  { pais: 'Bélgica', capital: 'Bruselas'},
  { pais: 'Belice', capital: 'Belmopán'},
  { pais: 'Benín', capital: 'Porto Novo y Cotonú'},
  { pais: 'Bielorrusia', capital: 'Minsk'},
  { pais: 'Birmania', capital: 'Naipyidó'},
  { pais: 'Bolivia', capital: 'Sucre'},
  { pais: 'Bosnia y Herzegovina', capital: 'Sarajevo'},
  { pais: 'Botsuana', capital: 'Gaborone'},
  { pais: 'Brasil', capital: 'Brasilia'},
  { pais: 'Brunéi', capital: 'Bandar Seri Begawan'},
  { pais: 'Bulgaria', capital: 'Sofía'},
  { pais: 'Burkina Faso', capital: 'Uagadugú'},
  { pais: 'Burundi', capital: 'Buyumbura'},
  { pais: 'Bután', capital: 'Timbu'},
  { pais: 'Cabo Verde', capital: 'Praia'},
  { pais: 'Camboya', capital: 'Nom Pen'},
  { pais: 'Camerún', capital: 'Yaundé'},
  { pais: 'Canadá', capital: 'Ottawa'},
  { pais: 'Catar', capital: 'Doha'},
  { pais: 'Chad', capital: 'Yamena'},
  { pais: 'Chile', capital: 'Santiago de Chile'},
  { pais: 'China', capital: 'Pekín'},
  { pais: 'Chipre', capital: 'Nicosia'},
  { pais: 'Ciudad del Vaticano', capital: 'Ciudad del Vaticano'},
  { pais: 'Colombia', capital: 'Bogotá'},
  { pais: 'Comoras', capital: 'Moroni'},
  { pais: 'Corea del Norte', capital: 'Pionyang'},
  { pais: 'Corea del Sur', capital: 'Seúl'},
  { pais: 'Costa de Marfil', capital: 'Yamusukro'},
  { pais: 'Costa Rica', capital: 'San José'},
  { pais: 'Croacia', capital: 'Zagreb'},
  { pais: 'Cuba', capital: 'La Habana'},
  { pais: 'Dinamarca', capital: 'Copenhague'},
  { pais: 'Dominica', capital: 'Roseau'},
  { pais: 'Ecuador', capital: 'Quito'},
  { pais: 'Egipto', capital: 'El Cairo'},
  { pais: 'El Salvador', capital: 'San Salvador'},
  { pais: 'Emiratos Árabes Unidos', capital: 'Abu Dabi'},
  { pais: 'Eritrea', capital: 'Asmara'},
  { pais: 'Eslovaquia', capital: 'Bratislava'},
  { pais: 'Eslovenia', capital: 'Liubliana'},
  { pais: 'España', capital: 'Madrid'},
  { pais: 'Estados Unidos', capital: 'Washington DC'},
  { pais: 'Estonia', capital: 'Tallin'},
  { pais: 'Etiopía', capital: 'Adís Abeba'},
  { pais: 'Filipinas', capital: 'Manila'},
  { pais: 'Finlandia', capital: 'Helsinki'},
  { pais: 'Fiyi', capital: 'Suva'},
  { pais: 'Francia', capital: 'París'},
  { pais: 'Gabón', capital: 'Libreville'},
  { pais: 'Gambia', capital: 'Banjul'},
  { pais: 'Georgia', capital: 'Tiflis'},
  { pais: 'Ghana', capital: 'Acra'},
  { pais: 'Granada', capital: 'Saint George'},
  { pais: 'Grecia', capital: 'Atenas'},
  { pais: 'Guatemala', capital: 'Ciudad de Guatemala'},
  { pais: 'Guyana', capital: 'Georgetown'},
  { pais: 'Guinea', capital: 'Conakri'},
  { pais: 'Guinea-Bisáu', capital: 'Bisáu'},
  { pais: 'Guinea Ecuatorial', capital: 'Malabo'},
  { pais: 'Haití', capital: 'Puerto Príncipe'},
  { pais: 'Honduras', capital: 'Tegucigalpa'},
  { pais: 'Hungría', capital: 'Budapest'},
  { pais: 'India', capital: 'Nueva Delhi'},
  { pais: 'Indonesia', capital: 'Yakarta'},
  { pais: 'Irak', capital: 'Bagdad'},
  { pais: 'Irán', capital: 'Teherán'},
  { pais: 'Irlanda', capital: 'Dublín'},
  { pais: 'Islandia', capital: 'Reikiavik'},
  { pais: 'Islas Marshall', capital: 'Majuro'},
  { pais: 'Islas Salomón', capital: 'Honiara'},
  { pais: 'Israel', capital: 'Jerusalén'},
  { pais: 'Italia', capital: 'Roma'},
  { pais: 'Jamaica', capital: 'Kingston'},
  { pais: 'Japón', capital: 'Tokio'},
  { pais: 'Jordania', capital: 'Amán'},
  { pais: 'Kazajistán', capital: 'Astaná'},
  { pais: 'Kenia', capital: 'Nairobi'},
  { pais: 'Kirguistán', capital: 'Biskek'},
  { pais: 'Kiribati', capital: 'Tarawa'},
  { pais: 'Kuwait', capital: 'Kuwait'},
  { pais: 'Laos', capital: 'Vientián'},
  { pais: 'Lesoto', capital: 'Maseru'},
  { pais: 'Letonia', capital: 'Riga'},
  { pais: 'Líbano', capital: 'Beirut'},
  { pais: 'Liberia', capital: 'Monrovia'},
  { pais: 'Libia', capital: 'Trípoli'},
  { pais: 'Liechtenstein', capital: 'Vaduz'},
  { pais: 'Lituania', capital: 'Vilna'},
  { pais: 'Luxemburgo', capital: 'Luxemburgo'},
  { pais: 'Madagascar', capital: 'Antananarivo'},
  { pais: 'Malasia', capital: 'Kuala Lumpur'},
  { pais: 'Malaui', capital: 'Lilongüe'},
  { pais: 'Maldivas', capital: 'Malé'},
  { pais: 'Malí', capital: 'Bamako'},
  { pais: 'Malta', capital: 'La Valeta'},
  { pais: 'Marruecos', capital: 'Rabat'},
  { pais: 'Mauricio', capital: 'Port-Louis'},
  { pais: 'Mauritania', capital: 'Nuakchot'},
  { pais: 'México', capital: 'Ciudad de México'},
  { pais: 'Micronesia', capital: 'Palikir'},
  { pais: 'Moldavia', capital: 'Chisináu'},
  { pais: 'Mónaco', capital: 'Mónaco'},
  { pais: 'Mongolia', capital: 'Ulán Bator'},
  { pais: 'Montenegro', capital: 'Podgorica'},
  { pais: 'Mozambique', capital: 'Maputo'},
  { pais: 'Namibia', capital: 'Windhoek'},
  { pais: 'Nauru', capital: 'Yaren'},
  { pais: 'Nepal', capital: 'Katmandú'},
  { pais: 'Nicaragua', capital: 'Managua'},
  { pais: 'Níger', capital: 'Niamey'},
  { pais: 'Nigeria', capital: 'Abuya'},
  { pais: 'Noruega', capital: 'Oslo'},
  { pais: 'Nueva Zelanda', capital: 'Wellington'},
  { pais: 'Omán', capital: 'Mascate'},
  { pais: 'Países Bajos', capital: 'Ámsterdam'},
  { pais: 'Pakistán', capital: 'Islamabad'},
  { pais: 'Palaos', capital: 'Melekeok'},
  { pais: 'Panamá', capital: 'Panamá'},
  { pais: 'Papúa Nueva Guinea', capital: 'Port Moresby'},
  { pais: 'Paraguay', capital: 'Asunción'},
  { pais: 'Perú', capital: 'Lima'},
  { pais: 'Polonia', capital: 'Varsovia'},
  { pais: 'Portugal', capital: 'Lisboa'},
  { pais: 'Reino Unido', capital: 'Londres'},
  { pais: 'República Centroafricana', capital: 'Bangui'},
  { pais: 'República Checa', capital: 'Praga'},
  { pais: 'República de Macedonia', capital: 'Skopie'},
  { pais: 'República del Congo', capital: 'Brazzaville'},
  { pais: 'República Democrática del Congo', capital: 'Kinsasa'},
  { pais: 'República Dominicana', capital: 'Santo Domingo'},
  { pais: 'República Sudafricana', capital: 'Ciudad Del Cabo'},
  { pais: 'Ruanda', capital: 'Kigali'},
  { pais: 'Rumanía', capital: 'Bucarest'},
  { pais: 'Rusia', capital: 'Moscú'},
  { pais: 'Samoa', capital: 'Apia'},
  { pais: 'San Cristóbal y Nieves', capital: 'Basseterre'},
  { pais: 'San Marino', capital: 'San Marino'},
  { pais: 'San Vicente y las Granadinas', capital: 'Kingstown'},
  { pais: 'Santa Lucía', capital: 'Castries'},
  { pais: 'Santo Tomé y Príncipe', capital: 'Santo Tomé'},
  { pais: 'Senegal', capital: 'Dakar'},
  { pais: 'Serbia', capital: 'Belgrado'},
  { pais: 'Seychelles', capital: 'Victoria'},
  { pais: 'Sierra Leona', capital: 'Freetown'},
  { pais: 'Singapur', capital: 'Singapur'},
  { pais: 'Siria', capital: 'Damasco'},
  { pais: 'Somalia', capital: 'Mogadiscio'},
  { pais: 'Sri Lanka', capital: 'Sri Jayewardenepura'},
  { pais: 'Suazilandia', capital: 'Babane y Lobamba'},
  { pais: 'Sudán', capital: 'Jartum'},
  { pais: 'Sudán del Sur', capital: 'Yuba'},
  { pais: 'Suecia', capital: 'Estocolmo'},
  { pais: 'Suiza', capital: 'Berna'},
  { pais: 'Surinam', capital: 'Paramaribo'},
  { pais: 'Tailandia', capital: 'Bangkok'},
  { pais: 'Tanzania', capital: 'Dodoma'},
  { pais: 'Tayikistán', capital: 'Dusambé'},
  { pais: 'Timor Oriental', capital: 'Dili'},
  { pais: 'Togo', capital: 'Lomé'},
  { pais: 'Tonga', capital: 'Nukualofa'},
  { pais: 'Trinidad y Tobago', capital: 'Puerto España'},
  { pais: 'Túnez', capital: 'Túnez'},
  { pais: 'Turkmenistán', capital: 'Asjabad'},
  { pais: 'Turquía', capital: 'Ankara'},
  { pais: 'Tuvalu', capital: 'Fongafale'},
  { pais: 'Ucrania', capital: 'Kiev'},
  { pais: 'Uganda', capital: 'Kampala'},
  { pais: 'Uruguay', capital: 'Montevideo'},
  { pais: 'Uzbekistán', capital: 'Taskent'},
  { pais: 'Vanuatu', capital: 'Port Vila'},
  { pais: 'Venezuela', capital: 'Caracas'},
  { pais: 'Vietnam', capital: 'Hanói'},
  { pais: 'Yemen', capital: 'Saná'},
  { pais: 'Yibuti', capital: 'Yibuti'},
  { pais: 'Zambia', capital: 'Lusaka'},
  { pais: 'Zimbabue', capital: 'Harare'}
];